mysql:
  host: 127.0.0.1
  port: 3306
  db: blog_db
  user: root
  config: charset=utf8mb4&parseTime=True&loc=Local
  password: root
  log_level: dev
logger:
  level: info
  prefix: hallu
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
upload:
  size: 2
  path: uploads/file
site_info:
  created_at: "2023-09-26"
  title: HalluTech
  qq_image: http://localhost/static/footer/qq.png
  version: 1.0.0
  email: 1085494156@qq.com
  wechat_image: http://localhost/static/footer/wechat.png
  name: HalluTech
  job: developer
  addr: Osaka
  slogan: HalluTech
  slogan_en: Hallu技术派
  web: http://www.hallutech.com/
  github_url: https://github.com/hoyyul
qq:
  app_id: xx
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
aws:
  enable: false
  bucket: hallu-blog
  region: ap-northeast-3
  access_key: AKIA5TVSSLD6IUZZVGIC
  secret_key: 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
email:
  host: smtp.qq.com
  port: 465
  sender_email: 1085494156@qq.com
  password: leuaiormlmrxiife
  sender_name: hallu
  use_ssl: true
  user_tls: false
jwt:
  secret_key: xxx
  expires: 5
  issuer: xx
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  pool_size: 100
es:
  host: http://127.0.0.1
  port: 9200
  user: ""
  password: ""
